### ISSUE TITLE
`.opml` support considered important

### ISSUE THREAD

**Issue by shenlebantongying** [emacs-eaf/eaf-rss-reader#3]
OPML is the most popular exchange format between RSS readers. eaf-rss-reader should consider support it to make migrate/exit to/from this one much easier.

The critical functionality is “import/export feeds from/to `.opml`”

**Comment by manateelazycat** [comment]
Thanks for suggestion, we will look it. ;)

**Comment by manateelazycat** [comment]
Looks https://github.com/emacs-eaf/eaf-rss-reader/commit/2f056707404d1cafc39c8ca4c6158067848b08e2

**Comment by ShaoChenHeng** [comment]
[96e78f8](https://github.com/emacs-eaf/eaf-rss-reader/commit/96e78f8f3c233170acbef1ed3d4a3dec1b2052d6)
support export .opml
