### ISSUE TITLE
反色选中效果兼容（黑白）

### ISSUE THREAD

**Issue by lijigang** [emacs-eaf/eaf-rss-reader#4]
![image](https://user-images.githubusercontent.com/4835998/140014545-a0483411-9fc9-4f29-8cf3-5a5f7086cfe6.png)

主题： https://github.com/rougier/nano-emacs

问题： 选中的文章，反向高亮效果差，变成黑色马塞克。

**Comment by ShaoChenHeng** [comment]
您确定更新到最新了吗？

我在安装nano-emacs后显示的效果是这样子的：

![pic](https://scheng52123.com/wp-content/uploads/2021/11/2021-11-03_21-30.png)

现在rss-reader的选中效果是背景色变暗。

**Comment by ShaoChenHeng** [comment]
> ![image](https://user-images.githubusercontent.com/4835998/140014545-a0483411-9fc9-4f29-8cf3-5a5f7086cfe6.png)
> 
> 主题： https://github.com/rougier/nano-emacs
> 
> 问题： 选中的文章，反向高亮效果差，变成黑色马塞克。

您确定更新到最新了吗？

我在安装nano-emacs后显示的效果是这样子的：

![pic](https://scheng52123.com/wp-content/uploads/2021/11/2021-11-03_21-30.png)

现在rss-reader的选中效果是背景色变暗。

**Comment by manateelazycat** [comment]
@lijigang 有问题再打开，请更新EAF
